baseURL: 'https://rowaaaaan.github.io/'
languageCode: en-us
title: Rowan
theme: PaperMod

params:
    profileMode:
        enabled: true
        title: "Hi, I'm known online as Rowan!" # optional default will be site title
        subtitle: "I'm a developer working mainly with C, C++, and Java 
          with experience in Web3 Solana development through Typescript, Vue.js, and Rust"
        imageUrl: "/images/profile.png" # optional
        imageTitle: "Profile picture of Rowan" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Github
              url: "https://github.com/rowaaaaan"
            - name: About Me
              url: "/about/"
            - name: Resume
              url: "/resume/"
            - name: Projects
              url: "/projects/"
            - name: Blog
              url: "/blog/"

    #socialIcons: # optional
        #name: "<platform>"
            #url: "<link>"
        #name: "<platform 2>"
            #url: "<link2>"
