baseURL: 'https://rowaaaaan.github.io/'
languageCode: en-us
title: Rowan
theme: PaperMod

params:
    profileMode:
        enabled: true
        title: "Hi, my name is Rowan!" # optional default will be site title
        subtitle: "I'm a developer working mainly with C, C++, C#, and Python.
            I also have some experience with Vanilla Js, Typescript, and Java. "
        imageUrl: "/images/profile.png" # optional
        imageTitle: "Profile picture of Rowan" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            #name: Archive
            #url: "#"
            - name: Github
              url: "https://github.com/rowaaaaan"
            - name: About Me
              url: "/aboutme/"
            - name: Projects
              url: "/projects/"
            - name: Blog
              url: "/blog/"

    #socialIcons: # optional
        #name: "<platform>"
            #url: "<link>"
        #name: "<platform 2>"
            #url: "<link2>"
